const repos = [
  {
    id: 255427872,
    full_name: "furkanyilmazx/generator-furkanyilmazx",
    description:
      "Node.js Rest API layered architecture template and React.js component(functional/class based) template generator",
    language: "JavaScript",
    stargazers_count: 8,
    forks: 0,
    html_url: "https://github.com/furkanyilmazx/generator-furkanyilmazx",
  },
  {
    id: 166709370,
    full_name: "furkanyilmazx/cra-antd-electron-boilerplate",
    description: "create react app, antdesign and electron app boilerplate",
    language: "JavaScript",
    stargazers_count: 4,
    forks: 0,
    html_url: "https://github.com/furkanyilmazx/cra-antd-electron-boilerplate",
  },
  {
    id: 266225929,
    full_name: "furkanyilmazx/furkanyilmazx.github.io",
    description: "furkanyilmazx's website",
    language: "JavaScript",
    stargazers_count: 3,
    forks: 0,
    html_url: "https://github.com/furkanyilmazx/furkanyilmazx.github.io",
  },
  {
    id: 169984850,
    full_name: "furkanyilmazx/rick-and-morty-app",
    description: "Rick and Morty Application",
    language: "JavaScript",
    stargazers_count: 3,
    forks: 2,
    html_url: "https://github.com/furkanyilmazx/rick-and-morty-app",
  },
  {
    id: 260573575,
    full_name: "furkanyilmazx/stm32f1103-samples",
    description: null,
    language: "C",
    stargazers_count: 1,
    forks: 0,
    html_url: "https://github.com/furkanyilmazx/stm32f1103-samples",
  },
  {
    id: 157904204,
    full_name: "furkanyilmazx/goReverseProxy",
    description: "Reverse proxy with golang and supporting websocket",
    language: "Go",
    stargazers_count: 1,
    forks: 0,
    html_url: "https://github.com/furkanyilmazx/goReverseProxy",
  },
  {
    id: 174481942,
    full_name: "furkanyilmazx/go2boot",
    description: null,
    language: "Go",
    stargazers_count: 1,
    forks: 0,
    html_url: "https://github.com/furkanyilmazx/go2boot",
  },
  {
    id: 190750842,
    full_name: "furkanyilmazx/ttany-chat-service",
    description: null,
    language: "Go",
    stargazers_count: 1,
    forks: 0,
    html_url: "https://github.com/furkanyilmazx/ttany-chat-service",
  },
  {
    id: 268367002,
    full_name: "furkanyilmazx/react-google-login",
    description: "A React Google Login Component",
    language: null,
    stargazers_count: 0,
    forks: 0,
    html_url: "https://github.com/furkanyilmazx/react-google-login",
  },
  {
    id: 260572191,
    full_name: "furkanyilmazx/simultaneous-annealing",
    description: null,
    language: "MATLAB",
    stargazers_count: 0,
    forks: 0,
    html_url: "https://github.com/furkanyilmazx/simultaneous-annealing",
  },
  {
    id: 260571236,
    full_name: "furkanyilmazx/serial-port-terminal",
    description: null,
    language: "C#",
    stargazers_count: 0,
    forks: 0,
    html_url: "https://github.com/furkanyilmazx/serial-port-terminal",
  },
  {
    id: 165929531,
    full_name: "furkanyilmazx/live-stream-control-app",
    description: null,
    language: "JavaScript",
    stargazers_count: 0,
    forks: 0,
    html_url: "https://github.com/furkanyilmazx/live-stream-control-app",
  },
  {
    id: 153825452,
    full_name: "furkanyilmazx/go2middlewarechain",
    description: "go2middlewarechain",
    language: null,
    stargazers_count: 0,
    forks: 0,
    html_url: "https://github.com/furkanyilmazx/go2middlewarechain",
  },
  {
    id: 167441729,
    full_name: "furkanyilmazx/aio-app",
    description: null,
    language: "JavaScript",
    stargazers_count: 0,
    forks: 0,
    html_url: "https://github.com/furkanyilmazx/aio-app",
  },
  {
    id: 169122549,
    full_name: "furkanyilmazx/npm-dind-jdk-git-jenkins_slave",
    description: null,
    language: "Dockerfile",
    stargazers_count: 0,
    forks: 0,
    html_url: "https://github.com/furkanyilmazx/npm-dind-jdk-git-jenkins_slave",
  },
  {
    id: 169123030,
    full_name: "furkanyilmazx/gitlab-docker",
    description: null,
    language: null,
    stargazers_count: 0,
    forks: 0,
    html_url: "https://github.com/furkanyilmazx/gitlab-docker",
  },
  {
    id: 168194128,
    full_name: "furkanyilmazx/kong-a-docker",
    description: null,
    language: "Dockerfile",
    stargazers_count: 0,
    forks: 0,
    html_url: "https://github.com/furkanyilmazx/kong-a-docker",
  },
  {
    id: 145025048,
    full_name: "furkanyilmazx/rest-in-model",
    description: "model based REST consumer library.",
    language: "JavaScript",
    stargazers_count: 0,
    forks: 0,
    html_url: "https://github.com/furkanyilmazx/rest-in-model",
  },
  {
    id: 140344800,
    full_name: "furkanyilmazx/hbt-ui",
    description: "hbt-ui css framework",
    language: "CSS",
    stargazers_count: 0,
    forks: 0,
    html_url: "https://github.com/furkanyilmazx/hbt-ui",
  },
  {
    id: 129555600,
    full_name: "furkanyilmazx/fGit",
    description: "Simple compress directory for projects and add timestamp",
    language: "Python",
    stargazers_count: 0,
    forks: 0,
    html_url: "https://github.com/furkanyilmazx/fGit",
  },
];

export default repos;
